### ISSUE TITLE
Containerize a deployment with docker

### ISSUE THREAD

**Issue by kianmehrabani** [comocheng/kineticmodelssite#129]
Use docker and docker-compose to containerize the webserver and database deployment.

**Comment by kianmehrabani** [comment]
Anaconda does not play well with docker containers, even with continuumio's own docker image. The solution is to use 'conda-run' to run the server in a conda environment, but this command does not direct output to stdout, meaning that we can't see output from the server or log it easily.
https://pythonspeed.com/articles/activate-conda-dockerfile/#working

**Comment by rwest** [comment]
Should we use `logging` more anyway?
