### ISSUE TITLE
Species on both sides of the reaction should have 2 stoichiometry entries

### ISSUE THREAD

**Issue by kianmehrabani** [comocheng/kineticmodelssite#137]

**Comment by rwest** [comment]
Actually, I think maybe they should.

There's a difference between
`A --> B `
and 
`A + C --> B + C`
and if you just think of stoichiometry coefficient as an int and say both reactions have nu_C = 0, then you lose that difference.

It's a bit of a pain.

**Comment by rwest** [comment]
I first read your issue title as "shouldn't" but see  now it's "should", which I agree with.
