### ISSUE TITLE
View: Reaction Detail

### ISSUE THREAD

**Issue by kianmehrabani** [comocheng/kineticmodelssite#31]
- [x] Reference material
- [x] Rate constants
- [ ] Pretty reaction equation
- [ ] Pretty rate equation
- [ ] Kinetic data plots
- [x] Links to reactants & products

**Comment by rwest** [comment]
NIST kinetics
https://kinetics.nist.gov/kinetics/ReactionSearch?r0=2229074&r1=7782447&r2=0&r3=0&r4=0&p0=2143682&p1=17778802&p2=0&p3=0&p4=0&expandResults=true&

Shows the reaction, with reactants as links.
Then a table of kinetics, with the actual numbers as well as source and a link to more detail. There's detailed biographic data as a "tooltip" 
![Screen Shot 2020-07-08 at 7 41 48 PM](https://user-images.githubusercontent.com/93807/86980882-165f1d80-c153-11ea-85d0-5f7597982514.png)

A button to create a comparison plot from selected rates, which looks like this:
(and contains a fit of the average of the selected rates).
![Screen Shot 2020-07-08 at 7 42 18 PM](https://user-images.githubusercontent.com/93807/86980922-31ca2880-c153-11ea-9795-b52a483b67a9.png)

**Comment by rwest** [comment]
RMG kinetics search.

https://rmg.mit.edu/database/kinetics/reaction/reactant1=multiplicity%202%0A1%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B4,S%7D%0A2%20H%20u0%20p0%20c0%20%7B1,S%7D%0A3%20H%20u0%20p0%20c0%20%7B1,S%7D%0A4%20H%20u0%20p0%20c0%20%7B1,S%7D%0A__reactant2=multiplicity%203%0A1%20O%20u1%20p2%20c0%20%7B2,S%7D%0A2%20O%20u1%20p2%20c0%20%7B1,S%7D%0A__product1=multiplicity%203%0A1%20O%20u2%20p2%20c0%0A__product2=multiplicity%202%0A1%20O%20u1%20p2%20c0%20%7B2,S%7D%0A2%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B3,S%7D%20%7B4,S%7D%20%7B5,S%7D%0A3%20H%20u0%20p0%20c0%20%7B2,S%7D%0A4%20H%20u0%20p0%20c0%20%7B2,S%7D%0A5%20H%20u0%20p0%20c0%20%7B2,S%7D%0A__res=True

![Screen Shot 2020-07-08 at 7 43 51 PM](https://user-images.githubusercontent.com/93807/86980996-62aa5d80-c153-11ea-90ae-dd4d55f85ec4.png)

The written out matjax equations might be pretty on an individual rate detail page, but on a long list they're much less helpful than a table of numbers like NIST have.
After much scrolling you get to the bottom where there is a plot:

![Screen Shot 2020-07-08 at 7 43 55 PM](https://user-images.githubusercontent.com/93807/86981054-89689400-c153-11ea-83e9-4001f90939d1.png)
you can toggle individual lines

You can click further into a specific reaction from a specific library
eg. https://rmg.mit.edu/database/kinetics/libraries/Dooley/methylformate/42/
![Screen Shot 2020-07-08 at 7 47 49 PM](https://user-images.githubusercontent.com/93807/86981206-ecf2c180-c153-11ea-8749-89da33e688ec.png)

**Comment by rwest** [comment]
PrIMe Kinetics
http://primekinetics.org:8080/#/search
Once found the reaction ID (eg. r00010621) from the reaction search, you can search for a reactionRate for that reaction_primeID:

![Screen Shot 2020-07-08 at 8 02 25 PM](https://user-images.githubusercontent.com/93807/86981944-fc730a00-c155-11ea-9206-f1f99dc4e3df.png)

then you can view the XML to get the rates

![Screen Shot 2020-07-08 at 8 02 33 PM](https://user-images.githubusercontent.com/93807/86981952-03018180-c156-11ea-9685-cd74829bf67d.png)
