### ISSUE TITLE
View: Species Detail

### ISSUE THREAD

**Issue by kianmehrabani** [comocheng/kineticmodelssite#44]
- [x] list of thermo should show something representative like ∆Hf(298K) and S(298K) (#116)
- [x] list of names could show which models used each name
- [x] list of thermo could show which models used each thermo
- [x] could have a link to a list of reactions that include that species (if the list is too long to include right there on the species detail page, perhaps it could be a link to the results of a "species search" form)

**Comment by kianmehrabani** [comment]
@rwest when displaying the list of names and the models that use it, how should we show when multiple models use the same name? I was implementing this change when I came across an example like this:

``` ('CH2', 'EL24115'),
 ('CH2', 'Fluorine'),
 ('CH2', 'GRI-17-species-mech'),
 ('CH2', 'GRI-mech-3.0'),
 ('CH2', 'NitrogenGlarborg2018'),
 ('CH2', 'USC_Mech_ii'),
 ('T-CH2', 'Narayanaswamy')
```
Should we show all of them? I am also trying to think of a way to display this that looks nice.

**Comment by rwest** [comment]
Could list them all. Or could just say the number. Or could have the number, and a popover with the names. Might be nice to be able to ctrl-F and search the page for a model name, which would be easiest if we just list them all. But could be comma separated in a paragraph with a smallish font so it doesn’t take too much space.


On Dec 19, 2020, at 3:44 PM, kianmehrabani <notifications@github.com> wrote:

﻿

@rwest<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frwest&data=04%7C01%7Cr.west%40northeastern.edu%7C85951fa185574d6c545f08d8a45ef1cb%7Ca8eec281aaa34daeac9b9a398b9215e7%7C0%7C0%7C637440074985085947%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PQKhSlzpZvf6qypuadf8jOc6HxhKSgCA0GvUMZI9IuQ%3D&reserved=0> when displaying the list of names and the models that use it, how should we show when multiple models use the same name? I was implementing this change when I came across an example like this:

 ('CH2', 'Fluorine'),
 ('CH2', 'GRI-17-species-mech'),
 ('CH2', 'GRI-mech-3.0'),
 ('CH2', 'NitrogenGlarborg2018'),
 ('CH2', 'USC_Mech_ii'),
 ('T-CH2', 'Narayanaswamy')


Should we show all of them? I am also trying to think of a way to display this that looks nice.
