### ISSUE TITLE
More useful info in list views before details

### ISSUE THREAD

**Issue by kianmehrabani** [comocheng/kineticmodelssite#61]
We want to show more useful data in the list view of the species/rxn search so the user doesn't have to click on the detail view all the time.

- [x] #95 
- [x] #96 
- [x] #113

**Comment by kianmehrabani** [comment]
@rwest I need some guidance here. Since there are a lot of options when looking at a species detail, what is important to show in each short entry on the search page?

**Comment by rwest** [comment]
Hmm. Good question.
1. There are probably no more than a handful of names in use for a species, so maybe could list them all.
2. A picture of a structure (or multiple structures, see #78)
3. Maybe some nugget of thermochemistry, like the ∆Hf at 298K.

Trying to think about SMILES or InChIs. Maybe both. Will usually only have one InChI (but should list all in case multiple), and a SMILES per structure? 

Any other suggestions?

**Comment by kianmehrabani** [comment]
Maybe some kind of aggregate metric like a count of kinetic models. We should also consider what summary info to put on the reaction entries.
